#!/bin/bash

# This hook checks debug messages in staged files and aborts the commit when one
# or more debug messages are found.

staged=`git diff --cached --name-only`

# Nothing to do
if [[ $staged = '' ]]; then
    exit 0
fi

echo -e "+ Checking debug messages in staged files..."

pattern="^\s*(var_dump|console.log)"

files=()
counter=0
for file in $staged; do
    if [[ -f $file && `ag $pattern $file` != '' ]]; then
        counter=$((counter + 1))
        files+=$file
    fi
done

if [[ $counter = 0 ]]; then
    echo -e "  + \033[1m\E[37;32mNo debug messages found\033[0m"
else
    echo -e "  + \E[31;5mDebug messages found in:\033[0m"

    for file in $files; do
        echo -e "     \033[1m - $file\033[0m"
    done;

    exit -1
fi

exit 0
