#!/bin/sh

if ! bspc wm -g &>/dev/null; then
  exit 1
fi

# Change cursor to pointer
xsetroot -cursor_name left_ptr

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors [ false, true ]
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Google-chrome desktop='^1' follow=off
bspc rule -a Chromium desktop='^1' follow=off
bspc rule -a qutebrowser desktop='^1' follow=on
bspc rule -a Slack desktop='^2' follow=off
bspc config external_rules_command $HOME/.config/bspwm/spotify

# Check monitors to define desktops
PRIMARY=""
SECONDARY=""

total=$(mons | grep enabled | wc -l)
for m in `mons | grep enabled | sed "s/\s\+/ /g" | cut -d' ' -f2 | sort`; do
    case "$m" in
        eDP1 )
            SECONDARY="$PRIMARY"
            PRIMARY="$m"
            ;;
        LVDS-1 )
            SECONDARY="$PRIMARY"
            PRIMARY="$m"
            ;;
        HDMI* )
            if [[ "$PRIMARY" == "" ]] || \
                    ([[ "$PRIMARY" != "DP1" ]] && \
                    [[ "$PRIMARY" != "eDP1" ]] && \
                    [[ "$PRIMARY" != "LVDS-1" ]]); then
                SECONDARY="$PRIMARY"
                PRIMARY="$m"
            else
                SECONDARY="$m"
            fi
            ;;
        DP* )
            if [[ "$PRIMARY" != "LVDS-1" ]] && [[ "$PRIMARY" != "eDP1" ]] \
                    || ([[ "$PRIMARY" == "eDP1" ]] && [[ $total -eq 3 ]]); then
                SECONDARY="$PRIMARY"
                PRIMARY="$m"
            else
                SECONDARY="$m"
            fi
            ;;
        VGA* )
            if  [[ "$PRIMARY" == "LVDS-1" ]]; then
               SECONDARY="VGA-1"
            else
                SECONDARY="$PRIMARY";
                PRIMARY="VGA-1"
            fi
            ;;
    esac
done;

echo "$PRIMARY" > /tmp/monitor
export PRIMARY=$PRIMARY

# Configure monitors
if [[ "$PRIMARY" != "LVDS-1" ]] && [[ "$PRIMARY" != "eDP1" ]]; then
    # Turn off built-in display
    xrandr --output eDP1 --off

    p=$(mons | grep " $PRIMARY " | cut -d':' -f1)
    s=$(mons | grep " $SECONDARY " | cut -d':' -f1)

    mons -S $p,$s:R
else
    mons -e left
fi

if [[ "$SECONDARY" == "" ]]; then
    bspc monitor $PRIMARY -d web im music code ssh email
else
    bspc monitor $PRIMARY -d web im music
    bspc monitor $SECONDARY -d code ssh email
fi

# Source the bspwm theme
if [[ -f $HOME/.config/bspwm/theme ]]; then
    source $HOME/.config/bspwm/theme
fi

# Launch applications on startup
if [[ -d $HOME/.autostart ]]; then
    for file in $(ls $HOME/.autostart); do
        sh $HOME/.autostart/$file
    done
fi
