#!/bin/sh

if ! bspc wm -g &>/dev/null; then
  exit 1
fi

# Change cursor to pointer
xsetroot -cursor_name left_ptr

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors [ false, true ]
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Google-chrome desktop='^1' follow=off
bspc rule -a Chromium desktop='^1' follow=off
bspc rule -a Hamster desktop='^1' follow=on
bspc rule -a qutebrowser desktop='^1' follow=on
bspc rule -a Slack desktop='^2' follow=off
bspc config external_rules_command $HOME/.config/bspwm/external

# Detect and load specific environment settings
[[ -f $HOME/.config/zsh/config/environments/$(hostname).sh ]] \
    && source $HOME/.config/zsh/config/environments/$(hostname).sh \
    || source $HOME/.config/zsh/config/environments/auto-detect.sh

# Configure bspwm for environment
[[ -f $HOME/.config/bspwm/environments/$(hostname).sh ]] \
    && source $HOME/.config/bspwm/environments/$(hostname).sh \
    || source $HOME/.config/bspwm/environments/auto-detect.sh

# Source the bspwm theme
if [[ -f $HOME/.config/bspwm/theme ]]; then
    source $HOME/.config/bspwm/theme
fi

# Launch applications on startup
if [[ -d $HOME/.autostart ]]; then
    for file in $(ls $HOME/.autostart); do
        sh $HOME/.autostart/$file
    done
fi
