#! /bin/sh

id=$1
instance=$3
class=$2
title=$(xdotool getwindowname "$id")

# Make VLC floating controls visible when in fullscreen
if [ "$instance" = vlc ] && [ "$title" = "vlc" ] ; then
    echo "layer=above"
fi
